spring:
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/agrodb?allowPublicKeyRetrieval=true
        username: fiap
        password: fiap

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect

    flyway:
        locations: classpath:migrations
        baseline-on-migrate: true

    rabbitmq:
        host: ${RABBITMQ_HOST:localhost}
        port: ${RABBITMQ_PORT:5672}
        username: guest
        password: guest

