spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/agrodb?allowPublicKeyRetrieval=true
    username: fiap
    password: fiap

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: guest
    password: guest

  mail:
    host: ${MAIL_HOTS:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_EMAIL:email@gmail.com}
    password: ${MAIL_PASSWORD:password}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: ${MAIL.HOTS:smtp.gmail.com}

server:
  port: ${PORT:8082}

job:
  email:
    notificacao: ${EMAIL_NOTIFICACAO:email@email.com}
